# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ViewshedQOS
                                 A QGIS plugin
 Run viewshed analysis based on our requirements.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-26
        copyright            : (C) 2023 by Mekki Benhamidouche
        email                : mekki99@hotmail.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ViewshedQOS class from file ViewshedQOS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .viewshed_qos import ViewshedQOS
    return ViewshedQOS(iface)
